version: '3.8'

services:
  laravel:
    build: .
    ports:
      - 80:80
    container_name: laravel
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    networks:
        - bayu-network
    volumes:
      - ./:/var/www
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

    depends_on:
      - psql
      - mysql

  psql:
    restart: always
    image: postgres
    container_name: pgdb
    volumes:
      - "./storage/app/public/postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    expose:
      - 5432
    ports:
      - "6543:5432"
    networks:
      - bayu-network

  mysql:
    image: mariadb
    container_name: mariadb
    volumes:
      - "./storage/app/public/mariadb:/var/lib/mysql"
    restart: always

    expose: 
      - 3306
    ports:
      - "6544:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: mysql
    networks:
      - bayu-network

networks:
  bayu-network:
    driver: bridge